/*
AnythingLLM Developer API

Testing EmbedAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_EmbedAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test EmbedAPIService V1EmbedEmbedUuidChatsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var embedUuid string

		resp, httpRes, err := apiClient.EmbedAPI.V1EmbedEmbedUuidChatsGet(context.Background(), embedUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EmbedAPIService V1EmbedEmbedUuidChatsSessionUuidGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var embedUuid string
		var sessionUuid string

		resp, httpRes, err := apiClient.EmbedAPI.V1EmbedEmbedUuidChatsSessionUuidGet(context.Background(), embedUuid, sessionUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EmbedAPIService V1EmbedEmbedUuidDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var embedUuid string

		resp, httpRes, err := apiClient.EmbedAPI.V1EmbedEmbedUuidDelete(context.Background(), embedUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EmbedAPIService V1EmbedEmbedUuidPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var embedUuid string

		resp, httpRes, err := apiClient.EmbedAPI.V1EmbedEmbedUuidPost(context.Background(), embedUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EmbedAPIService V1EmbedGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.EmbedAPI.V1EmbedGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EmbedAPIService V1EmbedNewPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.EmbedAPI.V1EmbedNewPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
