/*
AnythingLLM Developer API

Testing WorkspaceThreadsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_WorkspaceThreadsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test WorkspaceThreadsAPIService V1WorkspaceSlugThreadNewPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var slug string

		resp, httpRes, err := apiClient.WorkspaceThreadsAPI.V1WorkspaceSlugThreadNewPost(context.Background(), slug).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkspaceThreadsAPIService V1WorkspaceSlugThreadThreadSlugChatPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var slug string
		var threadSlug string

		resp, httpRes, err := apiClient.WorkspaceThreadsAPI.V1WorkspaceSlugThreadThreadSlugChatPost(context.Background(), slug, threadSlug).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkspaceThreadsAPIService V1WorkspaceSlugThreadThreadSlugChatsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var slug string
		var threadSlug string

		resp, httpRes, err := apiClient.WorkspaceThreadsAPI.V1WorkspaceSlugThreadThreadSlugChatsGet(context.Background(), slug, threadSlug).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkspaceThreadsAPIService V1WorkspaceSlugThreadThreadSlugDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var slug string
		var threadSlug string

		httpRes, err := apiClient.WorkspaceThreadsAPI.V1WorkspaceSlugThreadThreadSlugDelete(context.Background(), slug, threadSlug).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkspaceThreadsAPIService V1WorkspaceSlugThreadThreadSlugStreamChatPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var slug string
		var threadSlug string

		resp, httpRes, err := apiClient.WorkspaceThreadsAPI.V1WorkspaceSlugThreadThreadSlugStreamChatPost(context.Background(), slug, threadSlug).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkspaceThreadsAPIService V1WorkspaceSlugThreadThreadSlugUpdatePost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var slug string
		var threadSlug string

		resp, httpRes, err := apiClient.WorkspaceThreadsAPI.V1WorkspaceSlugThreadThreadSlugUpdatePost(context.Background(), slug, threadSlug).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
