/*
AnythingLLM Developer API

API endpoints that enable programmatic reading, writing, and updating of your AnythingLLM instance. UI supplied by Swagger.io.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the V1DocumentRemoveFolderDeleteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1DocumentRemoveFolderDeleteRequest{}

// V1DocumentRemoveFolderDeleteRequest struct for V1DocumentRemoveFolderDeleteRequest
type V1DocumentRemoveFolderDeleteRequest struct {
	Name *string `json:"name,omitempty"`
}

// NewV1DocumentRemoveFolderDeleteRequest instantiates a new V1DocumentRemoveFolderDeleteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1DocumentRemoveFolderDeleteRequest() *V1DocumentRemoveFolderDeleteRequest {
	this := V1DocumentRemoveFolderDeleteRequest{}
	return &this
}

// NewV1DocumentRemoveFolderDeleteRequestWithDefaults instantiates a new V1DocumentRemoveFolderDeleteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1DocumentRemoveFolderDeleteRequestWithDefaults() *V1DocumentRemoveFolderDeleteRequest {
	this := V1DocumentRemoveFolderDeleteRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V1DocumentRemoveFolderDeleteRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1DocumentRemoveFolderDeleteRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V1DocumentRemoveFolderDeleteRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V1DocumentRemoveFolderDeleteRequest) SetName(v string) {
	o.Name = &v
}

func (o V1DocumentRemoveFolderDeleteRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1DocumentRemoveFolderDeleteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableV1DocumentRemoveFolderDeleteRequest struct {
	value *V1DocumentRemoveFolderDeleteRequest
	isSet bool
}

func (v NullableV1DocumentRemoveFolderDeleteRequest) Get() *V1DocumentRemoveFolderDeleteRequest {
	return v.value
}

func (v *NullableV1DocumentRemoveFolderDeleteRequest) Set(val *V1DocumentRemoveFolderDeleteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1DocumentRemoveFolderDeleteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1DocumentRemoveFolderDeleteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1DocumentRemoveFolderDeleteRequest(val *V1DocumentRemoveFolderDeleteRequest) *NullableV1DocumentRemoveFolderDeleteRequest {
	return &NullableV1DocumentRemoveFolderDeleteRequest{value: val, isSet: true}
}

func (v NullableV1DocumentRemoveFolderDeleteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1DocumentRemoveFolderDeleteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


