/*
AnythingLLM Developer API

API endpoints that enable programmatic reading, writing, and updating of your AnythingLLM instance. UI supplied by Swagger.io.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the V1SystemRemoveDocumentsDeleteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1SystemRemoveDocumentsDeleteRequest{}

// V1SystemRemoveDocumentsDeleteRequest struct for V1SystemRemoveDocumentsDeleteRequest
type V1SystemRemoveDocumentsDeleteRequest struct {
	Names []string `json:"names,omitempty"`
}

// NewV1SystemRemoveDocumentsDeleteRequest instantiates a new V1SystemRemoveDocumentsDeleteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1SystemRemoveDocumentsDeleteRequest() *V1SystemRemoveDocumentsDeleteRequest {
	this := V1SystemRemoveDocumentsDeleteRequest{}
	return &this
}

// NewV1SystemRemoveDocumentsDeleteRequestWithDefaults instantiates a new V1SystemRemoveDocumentsDeleteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1SystemRemoveDocumentsDeleteRequestWithDefaults() *V1SystemRemoveDocumentsDeleteRequest {
	this := V1SystemRemoveDocumentsDeleteRequest{}
	return &this
}

// GetNames returns the Names field value if set, zero value otherwise.
func (o *V1SystemRemoveDocumentsDeleteRequest) GetNames() []string {
	if o == nil || IsNil(o.Names) {
		var ret []string
		return ret
	}
	return o.Names
}

// GetNamesOk returns a tuple with the Names field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SystemRemoveDocumentsDeleteRequest) GetNamesOk() ([]string, bool) {
	if o == nil || IsNil(o.Names) {
		return nil, false
	}
	return o.Names, true
}

// HasNames returns a boolean if a field has been set.
func (o *V1SystemRemoveDocumentsDeleteRequest) HasNames() bool {
	if o != nil && !IsNil(o.Names) {
		return true
	}

	return false
}

// SetNames gets a reference to the given []string and assigns it to the Names field.
func (o *V1SystemRemoveDocumentsDeleteRequest) SetNames(v []string) {
	o.Names = v
}

func (o V1SystemRemoveDocumentsDeleteRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1SystemRemoveDocumentsDeleteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Names) {
		toSerialize["names"] = o.Names
	}
	return toSerialize, nil
}

type NullableV1SystemRemoveDocumentsDeleteRequest struct {
	value *V1SystemRemoveDocumentsDeleteRequest
	isSet bool
}

func (v NullableV1SystemRemoveDocumentsDeleteRequest) Get() *V1SystemRemoveDocumentsDeleteRequest {
	return v.value
}

func (v *NullableV1SystemRemoveDocumentsDeleteRequest) Set(val *V1SystemRemoveDocumentsDeleteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SystemRemoveDocumentsDeleteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SystemRemoveDocumentsDeleteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SystemRemoveDocumentsDeleteRequest(val *V1SystemRemoveDocumentsDeleteRequest) *NullableV1SystemRemoveDocumentsDeleteRequest {
	return &NullableV1SystemRemoveDocumentsDeleteRequest{value: val, isSet: true}
}

func (v NullableV1SystemRemoveDocumentsDeleteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SystemRemoveDocumentsDeleteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


