/*
AnythingLLM Developer API

API endpoints that enable programmatic reading, writing, and updating of your AnythingLLM instance. UI supplied by Swagger.io.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner{}

// V1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner struct for V1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner
type V1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner struct {
	// Name of the attachment file
	Name string `json:"name"`
	// MIME type of the attachment
	Mime string `json:"mime"`
	// Base64 encoded content of the attachment
	ContentString string `json:"contentString"`
}

type _V1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner V1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner

// NewV1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner instantiates a new V1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner(name string, mime string, contentString string) *V1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner {
	this := V1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner{}
	this.Name = name
	this.Mime = mime
	this.ContentString = contentString
	return &this
}

// NewV1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInnerWithDefaults instantiates a new V1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInnerWithDefaults() *V1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner {
	this := V1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner{}
	return &this
}

// GetName returns the Name field value
func (o *V1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *V1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *V1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner) SetName(v string) {
	o.Name = v
}

// GetMime returns the Mime field value
func (o *V1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner) GetMime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mime
}

// GetMimeOk returns a tuple with the Mime field value
// and a boolean to check if the value has been set.
func (o *V1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner) GetMimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mime, true
}

// SetMime sets field value
func (o *V1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner) SetMime(v string) {
	o.Mime = v
}

// GetContentString returns the ContentString field value
func (o *V1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner) GetContentString() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContentString
}

// GetContentStringOk returns a tuple with the ContentString field value
// and a boolean to check if the value has been set.
func (o *V1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner) GetContentStringOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentString, true
}

// SetContentString sets field value
func (o *V1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner) SetContentString(v string) {
	o.ContentString = v
}

func (o V1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["mime"] = o.Mime
	toSerialize["contentString"] = o.ContentString
	return toSerialize, nil
}

func (o *V1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"mime",
		"contentString",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner := _V1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner)

	if err != nil {
		return err
	}

	*o = V1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner(varV1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner)

	return err
}

type NullableV1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner struct {
	value *V1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner
	isSet bool
}

func (v NullableV1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner) Get() *V1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner {
	return v.value
}

func (v *NullableV1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner) Set(val *V1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableV1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableV1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner(val *V1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner) *NullableV1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner {
	return &NullableV1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner{value: val, isSet: true}
}

func (v NullableV1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1WorkspaceSlugThreadThreadSlugChatPostRequestAttachmentsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


