/*
AnythingLLM Developer API

API endpoints that enable programmatic reading, writing, and updating of your AnythingLLM instance. UI supplied by Swagger.io.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the InvalidAPIKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvalidAPIKey{}

// InvalidAPIKey struct for InvalidAPIKey
type InvalidAPIKey struct {
	Message *string `json:"message,omitempty"`
}

// NewInvalidAPIKey instantiates a new InvalidAPIKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvalidAPIKey() *InvalidAPIKey {
	this := InvalidAPIKey{}
	return &this
}

// NewInvalidAPIKeyWithDefaults instantiates a new InvalidAPIKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvalidAPIKeyWithDefaults() *InvalidAPIKey {
	this := InvalidAPIKey{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *InvalidAPIKey) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvalidAPIKey) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *InvalidAPIKey) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *InvalidAPIKey) SetMessage(v string) {
	o.Message = &v
}

func (o InvalidAPIKey) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvalidAPIKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableInvalidAPIKey struct {
	value *InvalidAPIKey
	isSet bool
}

func (v NullableInvalidAPIKey) Get() *InvalidAPIKey {
	return v.value
}

func (v *NullableInvalidAPIKey) Set(val *InvalidAPIKey) {
	v.value = val
	v.isSet = true
}

func (v NullableInvalidAPIKey) IsSet() bool {
	return v.isSet
}

func (v *NullableInvalidAPIKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvalidAPIKey(val *InvalidAPIKey) *NullableInvalidAPIKey {
	return &NullableInvalidAPIKey{value: val, isSet: true}
}

func (v NullableInvalidAPIKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvalidAPIKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


